### PR TITLE
Adding check for ts field, if it's already set, then we don't set it

### PR DESCRIPTION
**Pull request by fx19880617**

### CODE REVIEW

**Comment by Raynos** [comment]
@fx19880617 

This does not solve the should `ts` be seconds or milliseconds problem. We need to make sure that `ts` is only ever one or the other.

**Comment by huawangpp** [comment]
Solves the breaking change problem - it doesn't overwrite ts field defined in dateFormats. So it doesn't break rt-logger. 

And the contact changes to - if ts dateFormats is not defined, by default, it is millsec.  If it is set, ts should be either millsec or sec based on the dateFormats value.

**Comment by fx19880617** [comment]
@Raynos You are correct, the correct thing maybe just using secondsSinceEpoch as field in the message to self explain the date format. As no one is enforce this, then different teams have their own standards. My fix is just by not changing existed ts field value.

**Comment by huawangpp** [comment]
@Raynos @fx19880617 

'ts' cannot be set to just one or the other w/o breaking the existing dateFormats feature, which I copied the details at the bottom. This feature is designed to config the dateFormats of ts and others. 

I agree that if the property name spells out a particular format, like secondsSinceEpoch, the format should be explicit.

Copied from the kafka-logger project -
dateFormats - An object of date formats to use; keys are the names of the keys the format should be added to, values are the names of the formats (useful for cross-language usage of the logs to reduce transforms on the consumers). These formats are: epoch (time in sec since Jan 1, 1970), jsepoch (time in ms since Jan 1, 1970), pyepoch (time in sec since Jan 1, 1970, but floating point with ms resolution), iso (ISO datestring format)

**Pull request merged**
